### PR TITLE
[accessibility] Align with Leaflet controls

### PR DESCRIPTION
**Pull request by Malvoz**
Upstream PR: https://github.com/Leaflet/Leaflet.fullscreen/pull/114.

The W3C [Maps for HTML Community Group](http://www.w3.org/community/maps4html/) is using this fork for their custom [`<mapml-viewer>`](https://github.com/Maps4HTML/Web-Map-Custom-Element) component, thank you for your work on this fork!

### CODE REVIEW

**Comment by Malvoz** [comment]
Bump... don't make me fork the fork! 😁

**Comment by Malvoz** [comment]
Thanks for merging this @runette. In hindsight I shouldn't have bumped the version to 1.0.5 in this PR and rather let you handle that. Anyhow, will the latest version be published to npm?

**Comment by runette** [comment]
To be honest - I meant to do it last week but ... too much work, I will try
to push it through in the next day or two.

**Comment by runette** [comment]
published as version 1.0.5

**Comment by Malvoz** [comment]
I had noticed, thanks!

**Pull request merged**
